<x-app-layout>   

    <div class="pt-16">
        <div class="relative py-8 sm:py-12">
        <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            {{-- Header --}}
            <div class="mb-8">
                <div class="flex items-center justify-between">
                    <div class="space-y-1">
                        <h2 class="text-2xl font-heading font-bold text-success-700">
                            Application Submitted Successfully
                        </h2>
                        <p class="text-sm font-medium text-success-600">
                            Your fundraising campaign is now under review
                        </p>
                    </div>
                    <div class="hidden sm:flex items-center space-x-2 text-sm text-success-600">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                        </svg>
                        <span>Submission Complete</span>
                    </div>
                </div>
            </div>
            <!-- Celebration Animation Container -->
            <div class="relative overflow-hidden">
                <!-- Animated Background Elements -->
                <div class="absolute inset-0 overflow-hidden pointer-events-none">
                    <div class="confetti-container">
                        <!-- Confetti will be generated by JavaScript -->
                    </div>
                </div>

                <!-- Main Success Card -->
                <div class="bg-white rounded-3xl shadow-2xl border border-neutral-100 overflow-hidden relative">
                    <!-- Success Header Section -->
                    <div class="bg-gradient-to-br from-success-500 via-success-600 to-success-700 px-8 py-12 text-center relative overflow-hidden">
                        <!-- Decorative Background Pattern -->
                        <div class="absolute inset-0 bg-white/10 transform -skew-y-6 origin-top-left"></div>
                        
                        <!-- Animated Success Icon -->
                        <div class="relative z-10">
                            <div class="success-icon-container mx-auto mb-6">
                                <div class="w-24 h-24 bg-white rounded-full flex items-center justify-center shadow-lg">
                                    <svg class="w-12 h-12 text-success-600 animate-check" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M5 13l4 4L19 7"/>
                                    </svg>
                                </div>
                            </div>
                            
                            <h1 class="text-4xl font-heading font-bold text-white mb-3">
                                🎉 Congratulations!
                            </h1>
                            <p class="text-xl text-success-100 mb-2">
                                Your donation application has been submitted successfully
                            </p>
                            <p class="text-success-200 text-sm">
                                Application #{{ $application->application_number }}
                            </p>
                        </div>
                    </div>

                    <!-- Application Details Section -->
                    <div class="p-8">
                        <div class="max-w-4xl mx-auto space-y-8">
                            <!-- Quick Summary Cards -->
                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div class="summary-card">
                                    <div class="flex items-center space-x-3 mb-3">
                                        <div class="w-10 h-10 bg-gradient-to-br from-primary-500 to-primary-600 rounded-xl flex items-center justify-center">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                                            </svg>
                                        </div>
                                        <div>
                                            <h3 class="font-heading font-bold text-neutral-800">Campaign Details</h3>
                                            <p class="text-sm text-neutral-600">Your fundraising information</p>
                                        </div>
                                    </div>
                                    <div class="space-y-2">
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Campaign Name:</span>
                                            <span class="text-sm font-medium text-neutral-800">{{ $application->applicant->contribution_name }}</span>
                                        </div>
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Target Amount:</span>
                                            <span class="text-sm font-medium text-success-600">
                                                @if($application->applicant->target_amount)
                                                    KES {{ number_format($application->applicant->target_amount, 2) }}
                                                @else
                                                    No target set
                                                @endif
                                            </span>
                                        </div>
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Beneficiary:</span>
                                            <span class="text-sm font-medium text-neutral-800">{{ $application->applicant->full_name }}</span>
                                        </div>
                                    </div>
                                </div>

                                <div class="summary-card">
                                    <div class="flex items-center space-x-3 mb-3">
                                        <div class="w-10 h-10 bg-gradient-to-br from-secondary-500 to-secondary-600 rounded-xl flex items-center justify-center">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                            </svg>
                                        </div>
                                        <div>
                                            <h3 class="font-heading font-bold text-neutral-800">Application Status</h3>
                                            <p class="text-sm text-neutral-600">Current processing stage</p>
                                        </div>
                                    </div>
                                    <div class="space-y-2">
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Application ID:</span>
                                            <code class="text-sm font-mono bg-neutral-100 px-2 py-1 rounded">{{ $application->application_number }}</code>
                                        </div>
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Submitted:</span>
                                            <span class="text-sm font-medium text-neutral-800">{{ $application->submitted_at->format('M j, Y \a\t g:i A') }}</span>
                                        </div>
                                        <div class="flex justify-between items-center">
                                            <span class="text-sm text-neutral-600">Status:</span>
                                            <span class="inline-flex items-center px-3 py-1 text-xs font-medium rounded-full 
                                                {{ $application->status->value === 'submitted' ? 'bg-secondary-100 text-secondary-700' : 'bg-neutral-100 text-neutral-700' }}">
                                                <span class="w-2 h-2 bg-current rounded-full mr-1 animate-pulse"></span>
                                                {{ ucfirst(str_replace('_', ' ', $application->status->value)) }}
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Next Steps Timeline -->
                            <div class="next-steps-section">
                                <div class="text-center mb-8">
                                    <h2 class="text-2xl font-heading font-bold text-neutral-800 mb-2">What Happens Next?</h2>
                                    <p class="text-neutral-600">Here's what to expect during the review process</p>
                                </div>

                                <div class="timeline-container">
                                    <div class="timeline-item active">
                                        <div class="timeline-marker completed">
                                            <svg class="w-4 h-4 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/>
                                            </svg>
                                        </div>
                                        <div class="timeline-content">
                                            <h3 class="timeline-title">Application Submitted</h3>
                                            <p class="timeline-description">Your application has been successfully received and is now in our system.</p>
                                            <span class="timeline-time">Just now</span>
                                        </div>
                                    </div>

                                    <div class="timeline-item">
                                        <div class="timeline-marker">
                                            <span class="timeline-number">2</span>
                                        </div>
                                        <div class="timeline-content">
                                            <h3 class="timeline-title">Review Process</h3>
                                            <p class="timeline-description">Our team will review your application and supporting documents for completeness and accuracy.</p>
                                            <span class="timeline-time">3-5 business days</span>
                                        </div>
                                    </div>

                                    <div class="timeline-item">
                                        <div class="timeline-marker">
                                            <span class="timeline-number">3</span>
                                        </div>
                                        <div class="timeline-content">
                                            <h3 class="timeline-title">Email Notification</h3>
                                            <p class="timeline-description">You'll receive updates at <strong>{{ $application->applicant->email }}</strong> about your application status.</p>
                                            <span class="timeline-time">Within review period</span>
                                        </div>
                                    </div>

                                    <div class="timeline-item">
                                        <div class="timeline-marker">
                                            <span class="timeline-number">4</span>
                                        </div>
                                        <div class="timeline-content">
                                            <h3 class="timeline-title">Campaign Launch</h3>
                                            <p class="timeline-description">Once approved, your donation campaign will go live and you can start sharing it with potential donors.</p>
                                            <span class="timeline-time">After approval</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Important Information -->
                            <div class="info-section">
                                <div class="bg-gradient-to-r from-secondary-50 to-orange-50 border border-secondary-200 rounded-2xl p-6">
                                    <div class="flex items-start space-x-4">
                                        <div class="w-10 h-10 bg-secondary-500 rounded-xl flex items-center justify-center mt-0.5">
                                            <svg class="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/>
                                            </svg>
                                        </div>
                                        <div>
                                            <h3 class="font-heading font-bold text-neutral-800 mb-3">Important Reminders</h3>
                                            <ul class="space-y-2 text-sm text-neutral-700">
                                                <li class="flex items-start space-x-2">
                                                    <svg class="w-4 h-4 text-secondary-500 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                                    </svg>
                                                    <span>Save your application number <strong>{{ $application->application_number }}</strong> for future reference</span>
                                                </li>
                                                <li class="flex items-start space-x-2">
                                                    <svg class="w-4 h-4 text-secondary-500 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                                    </svg>
                                                    <span>Keep your contact information updated to receive important notifications</span>
                                                </li>
                                                <li class="flex items-start space-x-2">
                                                    <svg class="w-4 h-4 text-secondary-500 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                                    </svg>
                                                    <span>We may request additional documents during the review process</span>
                                                </li>
                                                <li class="flex items-start space-x-2">
                                                    <svg class="w-4 h-4 text-secondary-500 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                                    </svg>
                                                    <span>Campaign approval is subject to our terms and conditions</span>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <!-- Action Buttons -->
                            <div class="text-center space-y-4">
                                <div class="flex flex-col sm:flex-row gap-4 justify-center">
                                    <a href="{{ route('dashboard') }}" class="btn-primary">                                        
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5"
                            stroke="currentColor" class="w-5 h-5 mr-2" class="w-4 h-4 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M3.75 6A2.25 2.25 0 0 1 6 3.75h2.25A2.25 2.25 0 0 1 10.5 6v2.25a2.25 2.25 0 0 1-2.25 2.25H6a2.25 2.25 0 0 1-2.25-2.25V6ZM3.75 15.75A2.25 2.25 0 0 1 6 13.5h2.25a2.25 2.25 0 0 1 2.25 2.25V18a2.25 2.25 0 0 1-2.25 2.25H6A2.25 2.25 0 0 1 3.75 18v-2.25ZM13.5 6a2.25 2.25 0 0 1 2.25-2.25H18A2.25 2.25 0 0 1 20.25 6v2.25A2.25 2.25 0 0 1 18 10.5h-2.25a2.25 2.25 0 0 1-2.25-2.25V6ZM13.5 15.75a2.25 2.25 0 0 1 2.25-2.25H18a2.25 2.25 0 0 1 2.25 2.25V18A2.25 2.25 0 0 1 18 20.25h-2.25A2.25 2.25 0 0 1 13.5 18v-2.25Z" />
                        </svg>
                                        Go to Dashboard
                                    </a>
                                    
                                    <a href="{{ route('active') }}" class="btn-secondary">
                                        <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                                        </svg>
                                        View Applications
                                    </a>
                                </div>
                                
                                <p class="text-sm text-neutral-500">
                                    Need help? <a href="#" class="text-primary-600 hover:text-primary-700 font-medium">Contact support</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>

    <!-- Enhanced Styles -->
    <style>
        /* Success Animation */
        @keyframes checkmark {
            0% {
                stroke-dashoffset: 100;
            }
            100% {
                stroke-dashoffset: 0;
            }
        }

        .animate-check {
            stroke-dasharray: 100;
            stroke-dashoffset: 100;
            animation: checkmark 0.6s ease-in-out 0.5s forwards;
        }

        @keyframes bounce-in {
            0% {
                transform: scale(0.3);
                opacity: 0;
            }
            50% {
                transform: scale(1.05);
            }
            70% {
                transform: scale(0.9);
            }
            100% {
                transform: scale(1);
                opacity: 1;
            }
        }

        .success-icon-container {
            animation: bounce-in 0.6s ease-out;
        }

       

        /* Confetti Animation */
        @keyframes confetti-fall {
            0% {
                transform: translateY(-100vh) rotate(0deg);
                opacity: 1;
            }
            100% {
                transform: translateY(100vh) rotate(360deg);
                opacity: 0;
            }
        }

        .confetti {
            position: absolute;
            width: 8px;
            height: 8px;
            background: linear-gradient(45deg, #10B981, #3B82F6);
            animation: confetti-fall 3s linear infinite;
        }
    </style>

    <!-- Confetti Animation Script -->
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            // Create confetti effect
            function createConfetti() {
                const confettiContainer = document.querySelector('.confetti-container');
                const colors = ['#10B981', '#3B82F6', '#F59E0B', '#EF4444', '#8B5CF6'];
                
                for (let i = 0; i < 50; i++) {
                    const confetti = document.createElement('div');
                    confetti.className = 'confetti';
                    confetti.style.left = Math.random() * 100 + '%';
                    confetti.style.background = colors[Math.floor(Math.random() * colors.length)];
                    confetti.style.animationDelay = Math.random() * 3 + 's';
                    confetti.style.animationDuration = (Math.random() * 3 + 2) + 's';
                    confettiContainer.appendChild(confetti);
                }
                
                // Remove confetti after animation
                setTimeout(() => {
                    confettiContainer.innerHTML = '';
                }, 6000);
            }
            
            // Trigger confetti after a short delay
            setTimeout(createConfetti, 500);
            
            // Add click effect to copy application number
            const appNumberElements = document.querySelectorAll('code');
            appNumberElements.forEach(element => {
                element.style.cursor = 'pointer';
                element.title = 'Click to copy';
                element.addEventListener('click', function() {
                    navigator.clipboard.writeText(this.textContent).then(() => {
                        const originalText = this.textContent;
                        this.textContent = 'Copied!';
                        this.style.background = '#10B981';
                        this.style.color = 'white';
                        
                        setTimeout(() => {
                            this.textContent = originalText;
                            this.style.background = '';
                            this.style.color = '';
                        }, 2000);
                    });
                });
            });
        });
    </script>
</x-app-layout>
